name: Déploiement Manuel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  NODE_VERSION: '18'

jobs:
  # Job de vérification rapide
  test:
    name: Tests Rapides
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Vérification des types TypeScript
        run: npm run type-check

      - name: Tests unitaires
        run: npm run test

      - name: Configuration de la base de données
        run: |
          npm run db:generate
          npm run db:push
          npm run db:seed
          echo "✅ Base de données configurée avec succès"

  # Job de déploiement
  deploy:
    name: Déploiement ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs: [test]
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement sur Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

      - name: Notification de déploiement
        run: |
          echo "🚀 Déploiement manuel terminé!"
          echo "Environnement: ${{ github.event.inputs.environment }}"
          echo "URL: ${{ github.event.inputs.environment == 'production' && secrets.PRODUCTION_URL || secrets.STAGING_URL }}"
          echo "Commit: ${{ github.sha }}"
          echo "Auteur: ${{ github.actor }}"


